export type StayReportItem = {
  customerName: string;
  customerAddress: string;
  customerId: string;
  mobileNumber: string;
  customerEmail?: string;
  totalGuests: string;
  checkinMode: string;
  reservationId: string;
  paymentStatus: string;
  totalAmount: number | string;
  paymentMode: string;
  roomNo: string;
  roomType: string;
  bedType: string;
  isVip: boolean;
  isForeignCustomer: boolean;
  noOfPax: number;
  childPax: number;
  extraPax: number;
  complimentary: string;
  status: string;
  paidAmount: string;
  checkInDate: string;
  checkOutDate: string;
  expectedCheckOutDate: string;
  graceTime: string;
  balanceAmount: number | string;
  extraServicesUsed: string[];
  feedbackRating?: string;
  idProofSubmitted: string;
};